name: Build OpenBLOX (Complete Rework)

on:
  push:
    branches: [Complete-Rework]
  pull_request:
    branches: [Complete-Rework]

jobs:
  build-ds:
    name: 🕹️ Build DS .nds
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v3

      - name: Build DS
        working-directory: ./C_Engine/Makefiles
        run: make -f makefile_ds

      - name: Upload OpenBLOX.nds
        uses: actions/upload-artifact@v3
        with:
          name: OpenBLOX.nds
          path: ./C_Engine/main.nds
