name: Build OpenBLOX DS

on:
  push:
    branches: [Complete-Rework]
  pull_request:
    branches: [Complete-Rework]

jobs:
  build-ds:
    name: 🕹️ Build DS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install devkitPro pacman
        run: |
          sudo apt update
          sudo apt install -y wget gnupg curl
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman

      - name: Install devkitARM and tools
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm nds-dev

      - name: Set environment variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH

      - name: Build NDS
        working-directory: ./C_Engine/Makefiles
        run: make -f makefile_ds

      - name: Upload OpenBLOX.nds
        uses: actions/upload-artifact@v3
        with:
          name: OpenBLOX.nds
          path: C_Engine/main.nds
